name: BasicTools
version: '@version@'
main: org.infinityminers.basictools.Main
api-version: 1.19
author: Vihara
website: infinityminers.org
description: Provides you with basic tools, that will full-fill your server's needs.